baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'SproutBox CoWorking Spaces'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: '© Copyright - Glisco Advisors LLP [CIN: AAD-9334] | Phone: +91.93192.11228 | Email: care@sproutbox.in | A System 3 Group Company'

seo:
  meta_og_title: "SproutBox CoWorking Spaces"
  meta_og_type: "website"
  meta_og_url: "https://sproutbox.in"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "SproutBox CoWorking Spaces are the right place to grow and scale your business, with on-demand office space, services backed agreements, and a proven service provider. SproutBox is your partner if you need an office space on demand"
  meta_twitter_card: "summary"
  meta_twitter_site: "@sproutboxin"
  meta_twitter_creator: "@sproutboxin"

collections:
  locations:
      output: true
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
